# Vehicle -> OCU (System monitoring purposes)
# Type 0 = long (int64), Type 2 = double (float64), Type 4 = string

float64 AutoGpsHead
float64 AutoGpsLat
float64 AutoGpsLon
float64 AutoGpsVel
int64   AutoGpsReferences
int64   AutoGpsQuality
float64 AutoGpsStamp
int64   pause
int64   key_on
int64   eng_enb
int64   pe7
int64   bbrake
int64   fbrake
float64 steerang
int64   throttle
int64   svp_enb_eng
int64   serialpck
int64   veh_gear
int64   veh_state
int64   veh_estop
int64   veh_obstacle
float64 vehicle_bat
string  run_composite
string  VehicleName
int64   Health_total
int64   rpm
int64   fuel
float64 sys_thd
