# Vehicle -> OCU (System monitoring purposes)
# Type 0 = long (int64), Type 2 = double (float64), Type 4 = string

float64 auto_gps_head
float64 auto_gps_lat
float64 auto_gps_lon
float64 auto_gps_vel
int64   auto_gps_references
int64   auto_gps_quality
float64 auto_gps_stamp
int64   pause
int64   key_on
int64   eng_enb
int64   pe7
int64   bbrake
int64   fbrake
float64 steerang
int64   throttle
int64   svp_enb_eng
int64   serialpck
int64   veh_gear
int64   veh_state
int64   veh_estop
int64   veh_obstacle
float64 vehicle_bat
string  run_composite
string  vehicle_name
int64   health_total
int64   rpm
int64   fuel
float64 sys_thd
